Story7/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('tugas.urls')),
]

tugas/urls.py
from . import views
from django.urls import path, include

app_name='tugas'

urlpatterns = [
        path('', views.homepage, name='home'),
        path('confirmation', views.confirmationpage, name = 'confirmation'),
]

tugas/models.py
from django.db import models

# Create your models here.
class Status(models.Model):
    name = models.CharField(max_length=50, unique=True)
    status = models.CharField(max_length=100, primary_key=True)

    def __str__(self):
        return self.status

tugas/forms.py
from django import forms
from .models import Status

class StatusForm(forms.Form):
    name = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'maxlength' : '50',
        'required' : True,
    }))
    status = forms.CharField(widget=forms.TextInput(attrs={
        'class' : 'form-control',
        'type' : 'text',
        'maxlength' : '100',
        'required' : True,
    }))

tugas/views.py
from django.shortcuts import render, redirect
from .forms import StatusForm
from .models import Status

# Create your views here.
def homepage(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if (form.is_valid()):
            newStatus = Status()
            newStatus.name = form.cleaned_data['name']
            newStatus.status = form.cleaned_data['status']
            response = {
                'name' : newStatus.name,
                'status' : newStatus.status,
            }
            return render(request,'confirmation.html', response)
    else:
        form = StatusForm()
    status = Status.objects.all()
    response = {'status': status, 'form':form}
    return render(request,'home.html', response)

def confirmationpage(request):
    if request.method == "POST":
        form = StatusForm(request.POST)
        if (form.is_valid()):
            newStatus = Status()
            newStatus.name = form.cleaned_data['name']
            newStatus.status = form.cleaned_data['status']
            newStatus.save()
        return redirect('/')
    else:
        form = StatusForm()
    response = {'form':form}
    return render(request,'confirmation.html', response)
    

tugas/templates/confirmation.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!--------------------------------------------------------- Required meta tags --------------------------------------------------------------->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!----------------------------------------------------------------- CSS ------------------------------------------------------------------->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Confirmation</title>
    <link rel="icon" type="image/gif/png" href="{% static 'Title.png'%}" />
    <style>
        * {
            padding: 0;
            margin: 0;
            box-sizing: border-box;
            scroll-behavior: smooth;
        }

        html {
            width: 100%;
            height: 100%;
            margin: 0;
            padding: 0;
            overflow-x: hidden;
        }

        body {
            background-image: linear-gradient(to left, #FFEAEC, #CDDA43);
        }

        ​ #confirmationTitle {
            text-shadow: 1px 0px 1px #CCCCCC, 0px 1px 1px #EEEEEE, 2px 1px 1px #CCCCCC, 1px 2px 1px #EEEEEE, 3px 2px 1px #CCCCCC, 2px 3px 1px #EEEEEE, 4px 3px 1px #CCCCCC, 3px 4px 1px #EEEEEE, 5px 4px 1px #CCCCCC, 4px 5px 1px #EEEEEE, 6px 5px 1px #CCCCCC, 5px 6px 1px #EEEEEE, 7px 6px 1px #CCCCCC;
            color: #35526F;
            font-family: Lucida Sans Unicode, Lucida Grande, sans-serif;
            font-size: 3vw;
            text-align: center !important;
            padding-top: 5vh;
        }

        #confirmationDescription {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            font-size: 1.75vw;
            color: rgb(106, 131, 156);
            font-style: normal;
            text-align: center;
            padding-top: 30px !important;
            padding-left: 2vw;
            padding-right: 2vw;
        }

        .form-group {
            padding-left: 35vw;
            padding-right: 35vw;
            font-family: Helvetica, Arial, sans-serif;
            font-weight: bold;
        }

        .form-label {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, Oxygen, Ubuntu, Cantarell, 'Open Sans', 'Helvetica Neue', sans-serif;
            font-size: 1vw;
            color: rgb(106, 131, 156);
        }

        .form-group input {
            max-width: 500px;
            background-color: #FFFFFF;
            border: 1px solid #000000;
            font-size: 20px;
            color: black;
        }

        #buttons button {
            background-color: #35526F;
            color: #ffffff;
            margin-right: 0.5vw;
        }

        #buttons a {
            background-color: #35526F;
            color: #ffffff;
            margin-left: 0.5vw;
        }

        #buttons button:hover {
            background-color: #e3f2fd;
            color: black;
            border: 1px solid #35526F !important;
        }

        #buttons a:hover {
            background-color: #e3f2fd;
            color: black;
            border: 1px solid #35526F !important;
        }
    </style>
</head>

<!----------------------------------------------------------------- CONFIRM --------------------------------------------------------------------->

<body>
    <h1>
        <div id="confirmationTitle" style="
        color: #35526F;
        font-family: Lucida Sans Unicode, Lucida Grande, sans-serif;
        font-size: 3vw;
        text-align: center !important;
        padding-top: 5vh;">Are you sure?</div>
    </h1>
    <h2>
        <div id="confirmationDescription">
            The status once posted will be here permanently.
        </div>
    </h2>
    <br>
    <form method="POST" action="{% url 'tugas:confirmation' %}">
        {% csrf_token %}
        <div class="form-group">
            <label for="name" class="form-label">Name</label><input type="text" class="form-control" id="name"
                name="name" maxlength="50" value="{{ name }}" readonly>
            <br>
            <label for="status" class="form-label">Status</label>
            <input type="text" class="form-control" id="status" name="status" maxlength="100" value="{{ status }}"
                readonly>
        </div>
        <br>
        <div id="buttons">
            <center><button type="submit" class="btn" name="yes">Yes</button>
                <a class="btn" href="{% url 'tugas:home' %}" role="button" name="no">No</a>
            </center>
        </div>
    </form>



    <!------------------------------------------------------------------ CSS ---------------------------------------------------------------------->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>

tugas/templates/home.html
<!doctype html>
{% load static %}
<html lang="en">

<head>
    <!--------------------------------------------------------- Required meta tags --------------------------------------------------------------->
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />

    <!----------------------------------------------------------------- CSS ------------------------------------------------------------------->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
        integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <title>Story 7</title>
    <link rel="icon" type="image/gif/png" href="{% static 'Title.png'%}" />
    <link rel="stylesheet" href="{% static 'css/main.css'%}" />
    <style>
        #buttons button {
            padding: 10px 15px;
            background-color: #35526F;
            color: #ffffff;
            margin-right: 0.5vw;
        }

        #buttons button:hover {
            background-color: #FFFFFF;
            color: black;
            border: 1px solid #FFFFFF !important;
        }
    </style>
</head>

<!----------------------------------------------------------------- HOMEPAGE ---------------------------------------------------------------------->

<body>
    <div id="hello">
        <div class="row one" style="margin-top:15%;">
            <div class="col-md-6">
                <form method="POST">
                    {% csrf_token %}
                    <h1 class="text" id="top">Hello!</h1>
                    <div class="form-group">
                        <input type="text" class="form-control" id="name" name="name" maxlength="50"
                            placeholder="Name">
                        <br>
                        <input type="text" class="form-control" id="status" name="status" maxlength="100"
                            placeholder="Status">
                        <button type="submit" class="btn" id="postStatus">Post Status</button>
                    </div>
                </form>
                <div id="buttons">
                    <button class="btn" onclick=changeColour() name="changeColour">Change Colour</button>
                </div>
            </div>
            <div class="col-md-8" id="statuses">
                <table class="table table-bordered table-hover text-center" style="border: 2px solid #35526F; margin-right: 15%; max-height: 35vh;
                overflow-y: scroll; max-width: 500px; 
                margin-bottom: 15%;">
                    <thead
                        style="border: 2px solid #35526F; background-color: #DFDFDF; color: #35526F; text-shadow: none;">
                        <tr>
                            <th scope="col" style="border: 1px solid #763829;">Name</th>
                            <th scope="col" style="border: 1px solid #35526F;">Status</th>
                        </tr>
                    </thead>
                    <tbody
                        style="border: 2px solid #35526F; text-align: center; color: #35526F; background-color: white;">
                        {% for i in status %}
                        <tr>
                            <th scope="row" style="font-weight: normal; border: 1px solid #35526F;">{{ i.name }}</th>
                            <td style="font-weight: normal; border: 1px solid #35526F;" class="statusForChallenge"
                                name="statusForChallenge">
                                {{ i.status }}</td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <script>
        function changeColour() {
            var elements = document.getElementsByClassName("statusForChallenge");
            for (var i = 0; i < elements.length; i++) {
                elements[i].style.color = "red";
            }
        }
    </script>


    <!------------------------------------------------------------------ CSS ---------------------------------------------------------------------->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous">
    </script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous">
    </script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous">
    </script>
</body>

</html>